#pragma once
#include <array>
#include "sirius/vulkan/core/vulkan.hpp"
extern "C" {
#include <libavutil/pixfmt.h>
}



namespace acma::vk {
    constexpr static std::array<VkFormat, AV_PIX_FMT_NB> pixel_format_mapping = {
        VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM, //AV_PIX_FMT_YUV420P
        VK_FORMAT_G8B8G8R8_422_UNORM,        //AV_PIX_FMT_YUYV422

        VK_FORMAT_R8G8B8_SRGB, //AV_PIX_FMT_RGB24
        VK_FORMAT_B8G8R8_SRGB, //AV_PIX_FMT_BGR24

        VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM, //AV_PIX_FMT_YUV422P
        VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM, //AV_PIX_FMT_YUV444P
        VK_FORMAT_UNDEFINED,                 //AV_PIX_FMT_YUV410P
        VK_FORMAT_UNDEFINED,                 //AV_PIX_FMT_YUV411P

        VK_FORMAT_R8_UNORM,  //AV_PIX_FMT_GRAY8
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_MONOWHITE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_MONOBLACK

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_PAL8

        VK_FORMAT_UNDEFINED,          //AV_PIX_FMT_YUVJ420P
        VK_FORMAT_UNDEFINED,          //AV_PIX_FMT_YUVJ422P
        VK_FORMAT_UNDEFINED,          //AV_PIX_FMT_YUVJ444P
        VK_FORMAT_B8G8R8G8_422_UNORM, //AV_PIX_FMT_UYVY422
        VK_FORMAT_UNDEFINED,          //AV_PIX_FMT_UYYVYY411

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BGR8
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BGR4
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BGR4_BYTE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_RGB8
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_RGB4
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_RGB4_BYTE

        VK_FORMAT_G8_B8R8_2PLANE_420_UNORM, //AV_PIX_FMT_NV12
        VK_FORMAT_UNDEFINED,                //AV_PIX_FMT_NV21

        VK_FORMAT_UNDEFINED,     //AV_PIX_FMT_ARGB
        VK_FORMAT_R8G8B8A8_SRGB, //AV_PIX_FMT_RGBA
        VK_FORMAT_UNDEFINED,     //AV_PIX_FMT_ABGR
        VK_FORMAT_B8G8R8A8_SRGB, //AV_PIX_FMT_BGRA

        VK_FORMAT_R16_UNORM, //AV_PIX_FMT_GRAY16BE
        VK_FORMAT_R16_UNORM, //AV_PIX_FMT_GRAY16LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV440P
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVJ440P
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA420P

        VK_FORMAT_R16G16B16_UNORM, //AV_PIX_FMT_RGB48BE
        VK_FORMAT_R16G16B16_UNORM, //AV_PIX_FMT_RGB48LE

        VK_FORMAT_R5G6B5_UNORM_PACK16, //AV_PIX_FMT_RGB565BE
        VK_FORMAT_R5G6B5_UNORM_PACK16, //AV_PIX_FMT_RGB565LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_RGB555BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_RGB555LE

        VK_FORMAT_B5G6R5_UNORM_PACK16, //AV_PIX_FMT_BGR565BE
        VK_FORMAT_B5G6R5_UNORM_PACK16, //AV_PIX_FMT_BGR565LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BGR555BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BGR555LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_VAAPI

        VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM, //AV_PIX_FMT_YUV420P16LE
        VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM, //AV_PIX_FMT_YUV420P16BE
        VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM, //AV_PIX_FMT_YUV422P16LE
        VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM, //AV_PIX_FMT_YUV422P16BE
        VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM, //AV_PIX_FMT_YUV444P16LE
        VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM, //AV_PIX_FMT_YUV444P16BE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_DXVA2_VLD

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_RGB444LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_RGB444BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BGR444LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BGR444BE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YA8

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BGR48BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BGR48LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV420P9BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV420P9LE
        VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM, //AV_PIX_FMT_YUV420P10BE
        VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM, //AV_PIX_FMT_YUV420P10LE
        VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM, //AV_PIX_FMT_YUV422P10BE
        VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM, //AV_PIX_FMT_YUV422P10LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV444P9BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV444P9LE
        VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM, //AV_PIX_FMT_YUV444P10BE
        VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM, //AV_PIX_FMT_YUV444P10LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV422P9BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV422P9LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRP
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRP9BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRP9LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRP10BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRP10LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRP16BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRP16LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA422P
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA444P
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA420P9BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA420P9LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA422P9BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA422P9LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA444P9BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA444P9LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA420P10BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA420P10LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA422P10BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA422P10LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA444P10BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA444P10LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA420P16BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA420P16LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA422P16BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA422P16LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA444P16BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA444P16LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_VDPAU

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_XYZ12LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_XYZ12BE

        VK_FORMAT_G8_B8R8_2PLANE_422_UNORM, //AV_PIX_FMT_NV16
        VK_FORMAT_UNDEFINED,                //AV_PIX_FMT_NV20LE
        VK_FORMAT_UNDEFINED,                //AV_PIX_FMT_NV20BE

        VK_FORMAT_R16G16B16A16_UNORM, //AV_PIX_FMT_RGBA64BE
        VK_FORMAT_R16G16B16A16_UNORM, //AV_PIX_FMT_RGBA64LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BGRA64BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BGRA64LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YVYU422

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YA16BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YA16LE

        VK_FORMAT_R8_UNORM,  //AV_PIX_FMT_GBRAP
        VK_FORMAT_R16_UNORM, //AV_PIX_FMT_GBRAP16BE
        VK_FORMAT_R16_UNORM, //AV_PIX_FMT_GBRAP16LE
    
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_QSV

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_MMAL

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_D3D11VA_VLD
    
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_CUDA
        
        VK_FORMAT_UNDEFINED,      //AV_PIX_FMT_0RGB
        VK_FORMAT_R8G8B8A8_UNORM, //AV_PIX_FMT_RGB0
        VK_FORMAT_UNDEFINED,      //AV_PIX_FMT_0BGR
        VK_FORMAT_B8G8R8A8_UNORM, //AV_PIX_FMT_BGR0

        VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM, //AV_PIX_FMT_YUV420P12BE
        VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM, //AV_PIX_FMT_YUV420P12LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV420P14BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV420P14LE
        VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM, //AV_PIX_FMT_YUV422P12BE
        VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM, //AV_PIX_FMT_YUV422P12LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV422P14BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV422P14LE
        VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM, //AV_PIX_FMT_YUV444P12BE
        VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM, //AV_PIX_FMT_YUV444P12LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV444P14BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV444P14LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRP12BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRP12LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRP14BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRP14LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVJ411P

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BAYER_BGGR8
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BAYER_RGGB8
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BAYER_GBRG8
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BAYER_GRBG8
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BAYER_BGGR16LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BAYER_BGGR16BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BAYER_RGGB16LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BAYER_RGGB16BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BAYER_GBRG16LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BAYER_GBRG16BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BAYER_GRBG16LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_BAYER_GRBG16BE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV440P10LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV440P10BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV440P12LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUV440P12BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_AYUV64LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_AYUV64BE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_VIDEOTOOLBOX

        VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16, //AV_PIX_FMT_P010LE
        VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16, //AV_PIX_FMT_P010BE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRAP12BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRAP12LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRAP10BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRAP10LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_MEDIACODEC

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GRAY12BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GRAY12LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GRAY10BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GRAY10LE

        VK_FORMAT_G16_B16R16_2PLANE_420_UNORM, //AV_PIX_FMT_P016LE
        VK_FORMAT_G16_B16R16_2PLANE_420_UNORM, //AV_PIX_FMT_P016BE
    
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_D3D11

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GRAY9BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GRAY9LE

        VK_FORMAT_R32_SFLOAT, //AV_PIX_FMT_GBRPF32BE
        VK_FORMAT_R32_SFLOAT, //AV_PIX_FMT_GBRPF32LE
        VK_FORMAT_R32_SFLOAT, //AV_PIX_FMT_GBRAPF32BE
        VK_FORMAT_R32_SFLOAT, //AV_PIX_FMT_GBRAPF32LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_DRM_PRIME
    
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_OPENCL

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GRAY14BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GRAY14LE

        VK_FORMAT_R32_SFLOAT, //AV_PIX_FMT_GRAYF32BE
        VK_FORMAT_R32_SFLOAT, //AV_PIX_FMT_GRAYF32LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA422P12BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA422P12LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA444P12BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_YUVA444P12LE

        VK_FORMAT_G8_B8R8_2PLANE_444_UNORM, //AV_PIX_FMT_NV24
        VK_FORMAT_UNDEFINED,                //AV_PIX_FMT_NV42

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_VULKAN

        VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16, //AV_PIX_FMT_Y210BE
        VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16, //AV_PIX_FMT_Y210LE

        VK_FORMAT_A2R10G10B10_UNORM_PACK32, //AV_PIX_FMT_X2RGB10LE
        VK_FORMAT_A2R10G10B10_UNORM_PACK32, //AV_PIX_FMT_X2RGB10BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_X2BGR10LE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_X2BGR10BE

        VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16, //AV_PIX_FMT_P210BE
        VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16, //AV_PIX_FMT_P210LE

        VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16, //AV_PIX_FMT_P410BE
        VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16, //AV_PIX_FMT_P410LE

        VK_FORMAT_G16_B16R16_2PLANE_422_UNORM, //AV_PIX_FMT_P216BE
        VK_FORMAT_G16_B16R16_2PLANE_422_UNORM, //AV_PIX_FMT_P216LE

        VK_FORMAT_G16_B16R16_2PLANE_444_UNORM, //AV_PIX_FMT_P416BE
        VK_FORMAT_G16_B16R16_2PLANE_444_UNORM, //AV_PIX_FMT_P416LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_VUYA

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_RGBAF16BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_RGBAF16LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_VUYX

        VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16, //AV_PIX_FMT_P012LE
        VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16, //AV_PIX_FMT_P012BE

        VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16, //AV_PIX_FMT_Y212BE
        VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16, //AV_PIX_FMT_Y212LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_XV30BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_XV30LE

        VK_FORMAT_R16G16B16A16_UNORM, //AV_PIX_FMT_XV36BE
        VK_FORMAT_R16G16B16A16_UNORM, //AV_PIX_FMT_XV36LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_RGBF32BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_RGBF32LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_RGBAF32BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_RGBAF32LE

        VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16, //AV_PIX_FMT_P212BE
        VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16, //AV_PIX_FMT_P212LE

        VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16, //AV_PIX_FMT_P412BE
        VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16, //AV_PIX_FMT_P412LE

        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRAP14BE
        VK_FORMAT_UNDEFINED, //AV_PIX_FMT_GBRAP14LE
    };
}